TPGrupo 6_Integrador de ProgramaciónIII/WebApp2.1/WebAppMvc/Models/ErrorViewModel.cs
namespace WebAppMvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TPGrupo 6_Integrador de ProgramaciónIII/WebApp2.1/WebAppMvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAppMvc.Models;

namespace WebAppMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult Demo()
        {
            return Content("Simple text plain", "text/html");
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TPGrupo 6_Integrador de ProgramaciónIII/WebApp2.1/WebAppMvc/Controllers/MailController.cs
using App.Core.Business;
using App.Core.Data;
using App.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebAppMvc.Controllers
{
    public class MailController : Controller
    {
        public static string UsuarioActual;
        MailsContext _dbContext;
        
        public MailController(MailsContext dbcontext)
        {
            _dbContext = dbcontext;
            
        }

        public IActionResult Index()
        {
            return View();
        }

        
        public IActionResult Enter(string user, string password)
        {
            UsuarioActual= user;
            try
            {
                var userEntity = _dbContext.Users.FirstOrDefault(u => u.UserName == user);

                if (userEntity != null)
                {
                    if (VerifyPassword(password, userEntity.UserPassword))
                    {
                        return Content("1"); // Credenciales válidas
                    }
                }

                return Content("Usuario y/o contraseña incorrecta");
            }
            catch (Exception ex)
            {
                return Content("Ocurrió un error: " + ex.Message);
            }
        }
        private bool VerifyPassword(string enteredPassword, string storedPassword)
        {
            
            return enteredPassword == storedPassword;
        }

        public IActionResult Detalle(int? id)
        {

            if (!id.HasValue 
                || id.Value <= 0)
            {
                return NotFound();
            }


            var mail = new Mail()
            {
                MailId = id.Value,
                Asunto = $"Asunto demo {id}",
                Contenido = $"Contenido demo {id}"
            };

            return View(mail);
        }
        
        public IActionResult MensajesEnviados(string remitente, string destinatario)
        {
            var user = UsuarioActual; // Reemplazar con el usuario actualmente autenticado

            var mensajes = _dbContext.Mails
                .Where(m => (m.Remitente == remitente && m.Destinatario == destinatario) ||
                            (m.Remitente == destinatario && m.Destinatario == remitente) ||
                            (m.Remitente == user && m.Destinatario == destinatario) ||
                            (m.Remitente == destinatario && m.Destinatario == user))
                .ToList();

            return View(mensajes);
        }



        public IActionResult Inbox()
        {
            var user = UsuarioActual/* User.Identity.Name*/; // Reemplaza con la lógica para obtener el usuario actualmente autenticado

            var mensajes = _dbContext.Mails
                .Where(m => m.Destinatario == user)
                .ToList();

            return View(mensajes);
        }
        public IActionResult Outbox()
        {
            var user = UsuarioActual/* User.Identity.Name*/; // Reemplaza con la lógica para obtener el usuario actualmente autenticado

            var mensajes = _dbContext.Mails
                .Where(m => m.Remitente == user)
                .ToList();

            return View(mensajes);
        }
        public IActionResult Enviar(string asunto, string contenido, string remitente, string destinatario)
        {
            try
            {
                
                var nuevoMail = new Mail
                {
                    Asunto = asunto,
                    Contenido = contenido,
                    Remitente = remitente,
                    Destinatario = destinatario
                };

                
                _dbContext.Mails.Add(nuevoMail);
                _dbContext.SaveChanges();

                return Content("El mensaje se envió correctamente");
            }
            catch (Exception ex)
            {
                return Content("Ocurrió un error al enviar el mensaje: " + ex.Message);
            }
        }

        public IActionResult Buscar(string buscar)
        {
            var user = UsuarioActual; 

            var mensajes = _dbContext.Mails
                .Where(m => m.Destinatario == user && m.Asunto.Contains(buscar)|| m.Remitente.Contains(buscar)|| m.Destinatario.Contains(buscar))
                .ToList();

            return View(mensajes);
        }

    }
}

TPGrupo 6_Integrador de ProgramaciónIII/WebApp2.1/WebAppMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Access";
}


<div class="row">
    <form id="frm">
        <div class="col-lg-6 col-lg-offset-3">
            Usuario
            <input type ="text" name="user"/>
            Password
            <input type="password" name="password"/>
        <input type="submit" class="btn btn-success" value="Entrar"/>
    </div>
    </form>
</div>

@{
    var a = 1;

}
@section Scripts
{

    <script>
        $(document).ready(function () {
            $("#frm").submit(function (e) {
                e.preventDefault();

                var url = "@Url.Content("~/Mail/Enter")";
                var parametros = $(this).serialize();

                $.post(url, parametros, function (data) {
                    if (data=="1"){
                    window.location.href = "@Url.Content("~/Mail")";
                    }else{
                        alert(data)
                    }
                });
            });
        });
    </script>

}

TPGrupo 6_Integrador de ProgramaciónIII/WebApp2.1/WebAppMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Demo">Demo</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mail" asp-action="Index">Mails</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mail" asp-action="Inbox">Inbox</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            <div>
                
            </div>
            @RenderBody()
            <div>
                
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebAppMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>